#!/bin/bash
wget http://download.geonames.org/export/zip/US.zip && unzip ./US.zip && rm ./US.zip ./readme.txt
cat US.txt | \
awk -F '\t' '{ \
  for (i = 1; i <= NF; i++) {
   gsub(/^[ \t]+|[ \t]+$/, "", $i); \
  } \
  print "{ \"countryCode\": \"" $1 \
  "\", \"postalCode\": \"" $2 \
  "\", \"placeName\": \"" $3 \
  "\", \"adminName1\": \"" $4 \
  "\", \"adminCode1\": \"" $5 \
  "\", \"adminName2\": \"" $6 \
  "\", \"adminCode2\": \"" $7 \
  "\", \"adminName3\": \"" $8 \
  "\", \"adminCode3\": \"" $9 \
  "\", \"location\": [ " (1 * $10) ", " (1 * $11) " ]"  \
  ", \"accuracy\": " (1 * $12) \
  " }" \
}' > zips.json
rm US.txt
